<a href="https://colab.research.google.com/github/MadhawaAponso/Pytorch-Learning/blob/main/Pytorch_Fundementals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.4.1+cu121


#Introduction to Tensors


In [2]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim # scaler has no dimensions. it is zero

0

In [4]:
vector = torch.tensor([7,7])

In [5]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [13]:
MATRIX = torch.tensor([[1,3],[2,3]])
MATRIX

tensor([[1, 3],
        [2, 3]])

In [11]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR.ndim

3

##random tensors

In [18]:
#creating random tensor
# we are giving the shape of the tensor here torch.rand(shape)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3463, 0.6110, 0.9999, 0.5935],
        [0.0090, 0.7591, 0.1186, 0.4396],
        [0.6604, 0.7885, 0.3044, 0.0666]])

In [20]:
rt2 = torch.rand(TENSOR.shape)
rt2

tensor([[[0.2153, 0.9749, 0.4431],
         [0.1943, 0.4732, 0.2478],
         [0.4322, 0.4494, 0.6729]]])

In [22]:
#creating random tensor with similar shape to an image tensor
rit = torch.rand(size =(3,224,224)) #this is color chanel , height , weight . there are 3 color chanels RGB , and height pixel and width : pixel
rit.ndim , rit.shape

(3, torch.Size([3, 224, 224]))

In [23]:
#tensor with all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
float_32_tensor = torch.tensor([1.0,2.0,3.0])
float_32_tensor.dtype

float_16_tensor = torch.tensor([1.0,2.0,3.0],dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [31]:
#Manupulating tensors
t1 = torch.rand(3)
t1

tensor([0.9483, 0.3442, 0.2658])

In [34]:
t1 =t1+100
t1

tensor([9582.8350, 3542.1455, 2757.9810])

In [35]:
t1=t1*100
t1

tensor([958283.5000, 354214.5625, 275798.0938])

## Matrix multiplication

In [36]:
torch.matmul(torch.rand(3,4) , torch.rand(3,4))
#this wont work as the inner dimension is not matching

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4)

In [37]:
torch.matmul(torch.rand(3,4) , torch.rand(4,3))
#The resulting tensor has the shape of outer dimensions

tensor([[0.8005, 0.6590, 1.1106],
        [0.7692, 0.8818, 0.7716],
        [0.3830, 0.5868, 0.6469]])